import Head from "next/head";
import Home from "../components/Home";
import Background from "../components/Background";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>The Dark Side Of The Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <Background />
        <Home />
      </main>
    </>
  );
}
